name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-24.04
            target: linux
          - name: Win64
            os: windows-2022
            target: msvc
            arch: x64
          - name: Win32
            os: windows-2022
            target: msvc
            arch: x86
          - name: AndroidV7A
            os: ubuntu-24.04
            target: android
            android_abi: armeabi-v7a
          - name: AndroidV8A
            os: ubuntu-24.04
            target: android
            android_abi: arm64-v8a
          - name: Android32
            os: ubuntu-24.04
            target: android
            android_abi: x86
          - name: Android64
            os: ubuntu-24.04
            target: android
            android_abi: x86_64
    env:
      ANDROID_PLATFORM: android-23
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Setup MSVC
        if: matrix.target == 'msvc'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Install Android NDK
        if: matrix.target == 'android'
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r23c

      - name: Configure toolchain
        shell: bash
        run: |
          args="-G Ninja -DCMAKE_BUILD_TYPE=Release"
          if [ "${{ matrix.target }}" = android ]; then
            args="$args -DCMAKE_TOOLCHAIN_FILE=${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake"
            args="$args -DANDROID_ABI=${{ matrix.android_abi }}"
            args="$args -DANDROID_PLATFORM=${{ env.ANDROID_PLATFORM }}"
            echo "GODOT_CPP_EXTRA_ARGS=-DGENERATE_DEBUG_SYMBOLS=OFF" >> "$GITHUB_ENV"
          elif [ "${{ matrix.target }}" = msvc ]; then
            echo "GODOT_CPP_EXTRA_ARGS=-DGODOT_DISABLE_EXCEPTIONS=OFF" >> "$GITHUB_ENV"
          fi
          echo "CMAKE_ARGS=$args" >> "$GITHUB_ENV"

      - name: Build godot-cpp
        shell: bash
        run: |
          cmake -S custom-godotcpp-build -B custom-godotcpp-build $CMAKE_ARGS $GODOT_CPP_EXTRA_ARGS
          cmake --build custom-godotcpp-build

      - name: Build library
        shell: bash
        run: |
          cmake -S . -B build $CMAKE_ARGS
          cmake --build build

      - name: Upload Built Library Artifact
        uses: actions/upload-artifact@v4
        with:
          path: addons/godot-openmpt/bin/*
          name: bin-${{ matrix.name }}
          if-no-files-found: error

  package:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Merge compiled binaries
        uses: actions/download-artifact@v4
        with:
          path: addons/godot-openmpt/bin
          pattern: bin-*
          merge-multiple: true
      - name: Upload output addon artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot-openmpt-${{ github.repository_id }}-${{ github.sha }}
          path: addons
